AllCops:
  Exclude:
    - db/schema.rb
    - spec/spec_helper.rb

LineLength:
  Max: 180

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 15

AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'bin/**/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/WordArray:
  Description: 'Use %w or %W for arrays of words.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#percent-w'
  Enabled: false

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 140

Metrics/PerceivedComplexity:
  Max: 8

# This is for modules like OpenURI that use snake case
Style/ConstantName:
  Description: 'Constants should use SCREAMING_SNAKE_CASE.'
  StyleGuide: 'https://github.com/bbatsov/ruby-style-guide#screaming-snake-case'
  Enabled: false
